name: Build & Deploy Blazor to GitHub Pages

# Триггер: всё, что пушится в main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Клонируем репозиторий вместе с полной историей
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Устанавливаем .NET 8 SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3) Сборка и публикация в папку publish
      - name: Publish Blazor WebAssembly
        run: dotnet publish -c Release --output publish

      # 4) Деплой в ветку gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages       # ветка для Pages
          publish_dir: ./publish/wwwroot # папка со статикой
          keep_files: false               # полностью перезаписывать ветку
