name: Build & Deploy Blazor to GitHub Pages

# 1) Дать права на запись в репо (по умолчанию GITHUB_TOKEN — только для чтения)
permissions:
  contents: write

on:
  push:
    branches:
      - master    
jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WebAssembly
        run: dotnet publish -c Release --output publish

      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: site-artifact
          path: publish/wwwroot

  deploy:
    name: Deploy to gh-pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (for push)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true   # <— сохраняем GITHUB_TOKEN в git

      - name: Download site artifact
        uses: actions/download-artifact@v3
        with:
          name: site-artifact
          path: publish/wwwroot

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./publish/wwwroot
          keep_files: false

